version: '3.6'
services:
  before-api:
    build: .
    container_name: before-api
    volumes:
      - .:/home/node/api
    depends_on:
      - before-postgres
      - before-redis
    links:
      - before-postgres
      - before-redis
    networks:
      - before-network
    command: bash -c "./run create-key && adonis serve --dev"
    ports:
      - 22200:3333
      - 22203:10000

  before-postgres:
    image: postgres
    container_name: before-postgres
    environment:
      - POSTGRES_USER=before
      - POSTGRES_PASSWORD=before
      - POSTGRES_DB=before
    ports:
      - '22201:5432'
    networks:
      - before-network

  before-redis:
    image: bitnami/redis
    container_name: before-redis
    environment:
      - REDIS_PASSWORD=before
    ports:
      - '22202:6379'
    networks:
      - before-network

networks:
  before-network:
    driver: bridge
